### ISSUE TITLE
Every Minute a Mail: Jemand hat sich in Ihren VELUX ACTIVE Account eingeloggt

### ISSUE THREAD

**Issue by ChWeiler** [Droccal/homebridge-velux-active#1]
homebridge-velux-active v1.0.0
Homebridge: [v1.5.1]

when I start the plugin, I get an email every minute:

Sehr geehrte/r VELUX ACTIVE Benutzer/in, |  
  |   |  
  | Jemand hat sich mit Ihrem VELUX ACTIVE Account xx@yy.de über die App VELUX ACTIVE am 07.11.22, 15:39 von Grolsheim, Deutschland* (ungefährer Standort, abgeleitet von der IP-Adresse: xx.xx.xx.xx) mit Ihrem Passwort iOSverbunden. |  
  |   |  
  | VELUX ACTIVEiOS07.11.22, 15:3987.123.47.224Grolsheim, Deutschland* |   | VELUX ACTIVEiOS07.11.22, 15:3987.123.47.224Grolsheim, Deutschland* | VELUX ACTIVE | iOS | 07.11.22, 15:39 | 87.123.47.224 | Grolsheim, Deutschland* |  
  | VELUX ACTIVEiOS07.11.22, 15:3987.123.47.224Grolsheim, Deutschland* | VELUX ACTIVE | iOS | 07.11.22, 15:39 | 87.123.47.224 | Grolsheim, Deutschland*
VELUX ACTIVE
iOS
07.11.22, 15:39
xx.xx.xx.xx
Grolsheim, Deutschland*

**Comment by Droccal** [comment]
Can you provide some details like error logs or something?

I know that you get the mail everytime you restart homebridge since it will do a new login (since I‘m not persisting the token). But it shouldn’t be really periodically doing a login. 

So something else might be broken.

**Comment by ChWeiler** [comment]
I uninstalled the plugin and then reinstalled it. Now it works fine.
