### ISSUE TITLE
only recive status and only can close windows

### ISSUE THREAD

**Issue by matzeeg3** [Droccal/homebridge-velux-active#3]
hi everyone,
i tryed to use this plugin but i am only able to see the actual status and i can close the windows but i am not able to open it.
has anyone else this problem?

kind regards
matze

**Comment by Droccal** [comment]
Hi Matthias, 

yes this is kind of expected. Velux has some secret keys and a few mechanisms to protect windows from being opened. Ive tried to reverse engineer their app and get across that but couldn‘t find any solution to produce the salted position the window accepts to open itself.

if you find a solution for that, i would be glad to implement it in this plugin :)
